#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

mv $OPENSHIFT_REPO_DIR/wsgi/web2py/applications $OPENSHIFT_DATA_DIR/
ln -s $OPENSHIFT_DATA_DIRapplications $OPENSHIFT_REPO_DIRwsgi/web2py/
ln -s $OPENSHIFT_REPO_DIRlibs/gluon $OPENSHIFT_REPO_DIRwsgi/web2py/
